### ISSUE TITLE
http://lmgtdfy.usopendata.org/ is broken

### ISSUE THREAD

**Issue by maxogden** [opendata/lmgtdfy#17]
![screen shot 2015-02-18 at 9 02 56 am](https://cloud.githubusercontent.com/assets/39759/6252135/f40ce548-b74c-11e4-814a-79614c37542e.png)

**Comment by sirkitree** [comment]
Currently seeing a "Bad Request (400)" error.

**Comment by waldoj** [comment]
We're working on it right now—thank you!

**Comment by waldoj** [comment]
Phew. It turns out that numbers in domain names were a problem, and that one request choked the whole site. There's a lesson learned. :)
