### ISSUE TITLE
Be able to specify directories to start inventory

### ISSUE THREAD

**Issue by jqnatividad** [opendata/lmgtdfy#22]
In NYC, most agencies are under the nyc.gov domain, e.g.

http://nyc.gov/html/dot - Dept of Transportation
http://nyc.gov/html/dcp - Dept of City Planning
http://nyc.gov/html/dcas - Dept of Citiywide Administrative Services
http://nyc.gov/html/doitt - Dept of Information Technology & Telecommunications

Would be nice if sites can be inventoried from a specific directory.

**Comment by waldoj** [comment]
I'm not sure if Bing's API supports that, but we can check it out!

**Comment by waldoj** [comment]
Unfortunately, Bing does not support this. They only support the `inurl:` option, e.g.:

`site:nyc.gov inurl:dot filetype:xls`

This would find every Excel file on `nyc.gov` that has `dot` _anywhere_ in the URL (e.g., `http://nyc.gov/html/dcp/dot.xls`. There appears to be no functionality that says that the URL's path component must _start_ with a given string, like `dot`.
