### ISSUE TITLE
Consider applying for GSOC 2015

### ISSUE THREAD

**Issue by jqnatividad** [opendata/lmgtdfy#28]
Google Summer of Code filing deadline is tomorrow.
https://www.google-melange.com/gsoc/homepage/google/gsoc2015
Perhaps the team can deputize future opendata hackers, not only for lmgtdfy, but for other projects too, and get Google to pick up the tab :)

**Comment by waldoj** [comment]
There was no way I could have applied yesterday, as it turned out, but thanks for the suggestion! :)
