### ISSUE TITLE
Searching to subdomains

### ISSUE THREAD

**Issue by PfeifferGov** [opendata/lmgtdfy#40]
Can you configure the app to permit searches to deeper than the top level?  Instead of a www.nj.gov search, configure so it can get to an agency, like http://www.nj.gov/dca/divisions/dlgs/  
Otherwise, this is way cool!

**Comment by waldoj** [comment]
I'm afraid that it's not possible. :( LMGTDFY uses Bing's API to get its results, and Bing's API does not provide any method of specifying that only URLs containing a particular string (e.g., `/dca/divisions/dlgs/`) should be included. Sorry!

**Comment by PfeifferGov** [comment]
Bummer there....BTW, if you didn't pick up on it - this is Marc Pfeiffer
from New Jersey.  I'm finally getting around to writing the report from the
Dodge event from February.  I'll be in touch more.....

Glad you got your funding stream re-started!  Your projects look very
good....but challening...

Marc

Marc Pfeiffer, Assistant Director
Bloustein Local Government Research Center
Bloustein School of Planning and Public Policy
33 Livingston Avenue
New Brunswick  NJ  08901
marc.pfeiffer@rutgers.edu
Office: 848-932-2830
Cell:  609-306-7513
